# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'WelaaaV2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WelaaaV2
  
  # Firebase Analytics + Firebase Cloud Message
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Messaging'
  
  # Fabric
  pod 'Fabric'
  pod 'Crashlytics'
  
  # Facebook SDKs
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  # KakaoOpenSDK
  pod 'KakaoOpenSDK'

  # AFNetworking
  pod 'AFNetworking', '~> 3.0'
  
  # KeyChain
  pod 'SAMKeychain'
  
  # Toast message
  pod 'Toast', '~> 4.0.0'

  # Showing images from web
  pod 'SDWebImage', '~> 4.0'

  
  # Third party deps podspec link  
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'DevSupport',
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket',
      'RCTImage',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          
          # The following is needed to ensure the "archive" step works in XCode.
          # It removes React & Yoga from the Pods project, as it is already included in the main project.
          # Without this, you'd see errors when you archive like:
          # "Multiple commands produce ... libReact.a"
          # "Multiple commands produce ... libyoga.a"
          
          targets_to_ignore = %w(React yoga)
          
          if targets_to_ignore.include? target.name
              target.remove_from_project
          end
          
      end
  end

end
