# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'WelaaaV2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Firebase Analytics + Firebase Cloud Message
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'

    # Fabric
    pod 'Fabric'
    pod 'Crashlytics'

    # Facebook SDKs
    pod 'Bolts'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'

    # KakaoOpenSDK
    pod 'KakaoOpenSDK'

    # Video Player
    # pod 'PlayerKit'


end